[package]
name = "tic-tac-toe"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/DoctorDalek1963/tic-tac-toe"
license = "MIT"

[lib]
name = "tictactoe"
path = "src/lib.rs"

[dependencies]
eframe = "0.19.0"
itertools = "0.10.5"
rand = "0.8.5"
rayon = "1.5.3"
thiserror = "1.0.37"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "eval_and_minimax"
harness = false
